# Generated by Django 6.0.1 on 2026-02-23 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='VideoProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('original_title', models.OneToOneField(blank=True, help_text='Связь с оригинальным названием; допускается пустое значение', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema.originaltitle')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.producttype')),
            ],
        ),
    ]
