# Generated by Django 6.0.1 on 2026-02-23 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='DirectorVideoProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.director')),
                ('video_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.videoproduct')),
            ],
            options={
                'verbose_name': 'director–video product relation',
                'verbose_name_plural': 'director–video product relations',
            },
        ),
    ]
