# Generated by Django 6.0.1 on 2026-02-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_director_directorvideoproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproduct',
            name='directors',
            field=models.ManyToManyField(related_name='video_products', through='cinema.DirectorVideoProduct', to='cinema.director'),
        ),
    ]
